pciemgr: add more unit tests

diff --git a/platform/src/lib/pcietlp/tests/pcietlp/run_enc_tests b/platform/src/lib/pcietlp/tests/pcietlp/run_enc_tests
--- a/platform/src/lib/pcietlp/tests/pcietlp/run_enc_tests
+++ b/platform/src/lib/pcietlp/tests/pcietlp/run_enc_tests
@@ -4,12 +4,13 @@ npass=0
 nfail=0
 for tc in testcases/*.enc; do
     tb=`echo $tc | sed -e 's/\.enc$//'`
-    pcietlp.gen -e $tc > $tb.out
-    if ! cmp -s $tb.out $tb.exp; then
-	echo $tc FAILED ===
+    ./pcietlp.gen -e $tc > $tb.out
+    if ! cmp -s $tb.exp $tb.out; then
+	printf "%-30s FAILED ***\n" $tc
+	diff $tb.exp $tb.out
 	nfail=`expr $nfail + 1`
     else
-	echo $tc passed
+	printf "%-30s passed\n" $tc
 	rm $tb.out
 	npass=`expr $npass + 1`
     fi
diff --git a/platform/src/lib/pcietlp/tests/pcietlp/verify_enc_tests b/platform/src/lib/pcietlp/tests/pcietlp/verify_enc_tests
--- a/platform/src/lib/pcietlp/tests/pcietlp/verify_enc_tests
+++ b/platform/src/lib/pcietlp/tests/pcietlp/verify_enc_tests
@@ -4,12 +4,13 @@ npass=0
 nfail=0
 for tc in testcases/*.enc; do
     tb=`echo $tc | sed -e 's/\.enc$//'`
-    pcietlp.gen -d $tb.exp > $tb.out
-    if ! cmp -s $tb.out $tb.enc; then
-	echo $tc FAILED ===
+    ./pcietlp.gen -d $tb.exp > $tb.out
+    if ! cmp -s $tb.enc $tb.out; then
+	printf "%-30s FAILED ***\n" $tc
+	diff $tb.enc $tb.out
 	nfail=`expr $nfail + 1`
     else
-	echo $tc verified
+	printf "%-30s verified\n" $tc
 	rm $tb.out
 	npass=`expr $npass + 1`
     fi
