Fixing trivial coverage issues (#1575)

diff --git a/nic/tools/run-coverage b/nic/tools/run-coverage
--- a/nic/tools/run-coverage
+++ b/nic/tools/run-coverage
@@ -11,8 +11,8 @@ if [[ $? -ne 4 ]]; then
     exit 1
 fi
 
-OPTIONS="kc:"
-LONGOPTIONS="keep-data,configfile:"
+OPTIONS="kic:"
+LONGOPTIONS="keep-data,configfile:,ignore-errors"
 
 PARSED=$(getopt --options=$OPTIONS --longoptions=$LONGOPTIONS --name "$0" -- "$@")
 if [[ $? -ne 0 ]]; then
@@ -27,6 +27,7 @@ eval set -- "$PARSED"
 
 config_file="coverage.json"
 keep_data=0
+ignore_errors=0
 while true; do
     case "$1" in
         -k |--keep-data)
@@ -36,6 +37,10 @@ while true; do
         -c|--config-file)
             config_file=$2
             shift 2
+            ;;
+        -i|--ignore-errors)
+            ignore_errors=1
+            shift
             ;;
         --)
             shift
@@ -57,6 +62,10 @@ if [ $keep_data -eq 0 ];then
     rm -f $MPU_COV_DUMP_FILE
 fi
 
+if [ $ignore_errors -eq 1 ];then
+    export IGNORE_ERRORS=--ignore-errors
+fi
+
 export MPU_COV_DUMP_FILE=$NIC_DIR/coverage/asm_cov.dump
 export MPU_PC_COV_DUMP_DIR=$NIC_DIR/coverage/asm_out_all
 
@@ -74,5 +83,11 @@ if [ $OUT -ne 0 ];then
    echo "Dol coverage run generation failed!"
    exit 1
 fi
-$NIC_DIR/tools/gcov/run.py --config $config_file 2>&1 | tee $NIC_DIR/coverage.log
+set -o pipefail
+$NIC_DIR/tools/gcov/run.py $IGNORE_ERRORS --config $config_file 2>&1 | tee $NIC_DIR/coverage.log
+OUT=$?
+if [ $OUT -ne 0 ];then
+   echo "Coverage run failed."
+   exit 1
+fi
 rm -f $MPU_COV_DUMP_FILE
