Add coverage to include dol jobs (#1013)
* Add coverage to include dol jobs

* Remove rxdma and txdma from code coverage for now

* Clean up gcda files after each run from model

diff --git a/nic/tools/run-coverage b/nic/tools/run-coverage
--- a/nic/tools/run-coverage
+++ b/nic/tools/run-coverage
@@ -5,4 +5,10 @@ fi
 export COVERAGE_CONFIG_PATH=$NIC_DIR/conf/
 export COVERAGE_OUTPUT=$NIC_DIR/gen/coverage
 export OBJ_DIR=$NIC_DIR/obj
+$NIC_DIR/tools/gen_dol_cov_run.py
+OUT=$?
+if [ $OUT -ne 0 ];then
+   echo "Dol coverage run generation failed!"
+   exit 1
+fi
 $NIC_DIR/tools/gcov/run.py 2>&1 | tee $NIC_DIR/coverage.log
